swagger: "2.0"
info:
  version: 1.0.0
  title: Eleições 2016
  description: API de consulta de candidatos para as eleições de 2016 baseado nos dados do tribunal superior eleitoral
  termsOfService: http://swagger.io/terms/
  contact:
    name: Americo Neto
    email: americoneto1@gmail.com
    url: http://api-eleicoes.herokuapp.com
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: api-eleicoes.herokuapp.com
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /candidatos/{uf}:
    get:
      description: Retorna os candidatos por estado.
      operationId: findCandidatos
      parameters:
        - name: uf
          in: path
          description: Estado do candidato
          required: true
          type: string
          format: string
        - name: skip
          in: query
          description: Quantidade de registros para paginação
          required: false
          type: integer
          format: int32
        - name: top
          in: query
          description: Limite de registros para paginação
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: Dados básicos dos candidatos
          schema:
            $ref: '#/definitions/Candidato'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /candidato/{numero}:
    get:
      description: Retorna os dados do candidato por numero.
      operationId: findCandidato
      parameters:
        - name: numero
          in: path
          description: Numero do candidato
          required: true
          type: string
          format: string
      responses:
        200:
          description: dados do candidato
          schema:
            $ref: '#/definitions/CandidatoData'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /candidato/{numero}/bens:
    get:
      description: Retorna os dados dos bens do candidato.
      operationId: findPets
      parameters:
        - name: numero
          in: path
          description: Numero do candidato
          required: true
          type: string
          format: string
      responses:
        200:
          description: dados dos candidatos
          schema:
            $ref: '#/definitions/Bem'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Candidato:
    allOf:
      - $ref: '#/definitions/CandidatoData'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  CandidatoData:
    properties:
      username:
        description: User supplied username
        type: string
        minLength: 4
        example: John78
      firstName:
        description: User first name
        type: string
        minLength: 1
        example: John
      lastName:
        description: User last name
        type: string
        minLength: 1
        example: Smith
      email:
        description: User email address
        type: string
        format: email
        example: john.smith@example.com
  Bem:
    properties:
      nome:
        type: string
      valor:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string